version: '3'

services:
  application:
    build:
      context: .
      dockerfile: ./wec.dockerfile
    # image: tbot/tbot-driver:0.1.0
    restart: always
    volumes:
      - ./app:/app
    command: python3 main.py
    